[package]
name = "toml_to_json"
version = "0.1.0"
authors = ["Sander Hahn <sanderhahn@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.103"
toml = "0.5.5"
serde_json = "1.0.42"

[profile.release]
opt-level = 'z'
lto = true
